Dict{Symbol, Any}(
    :album_id => SpAlbumId("2O9mD7oKwBnhQZQUAJM6GM"),
    :album_ids => SpAlbumId.(["2O9mD7oKwBnhQZQUAJM6GM", "3eLvDNfWAMpytqIp073FEc"]),
    :artist_id => SpArtistId("7HGFXtBhRq3g1Ma3nH4Rgv"),
    :artist_ids => SpArtistId.(["2CIMQHirSU0MQqyYHq0eOx", "57dN52uHvrHOxijzpIgu3E", "1vCWHaC5f2uS3yhpwWbIA6"]),
    :category_id => SpCategoryId("0JQ5DAqbMKFEC4WFtoNRpw"),
    :category_name => "pop", 
    :country => get_user_country(),
    :episode_id => SpId("7Hyyvc9QaojDudrjXsS06P"),
    :episode_ids => [SpEpisodeId(), SpEpisodeId("7Hyyvc9QaojDudrjXsS06P")],
    :ids => [SpId("74ASZWbe4lXaubB36ztrGX"), SpId("08td7MxkoHQkXnWAYD8d6Q")],
    :include_groups => "album,single,appears_on,compilation",
    :item_type => "artist",
    :limit => 10,
    :locale => "",
    :market => get_user_country(),
    :noffset => 0,
    :offset => 0,
    :playlist_name => "Playlist name",
    :playlist_id => SpPlaylistId("3cEYpjA9oz9GiPac4AsH4n"),
    :q => "Coldplay",
    :seeds => [SpId("4NHQUGzhtTLFvgF5SZesLK"), SpId("79O1dBolRj3Epn1pIZRCsZ")],
    :seeds_dict =>  Dict("seed_artists" => SpArtistId("0YC192cP3KPCRWx8zr8MfZ")),
    :show_id => SpShowId("72qiPaoDRf8HkGKEChvG5q"),
    :show_ids => SpShowId.(["5AvwZVawapvyhJUIx71pdJ", "6ups0LMt1G8n81XLlkbsPo"]),
    :time_range => "medium",
    :timestamp => now(),
    :track_attributes => Dict("max_danceability" => "0.80"), 
    :track_id => SpTrackId("0WdUHon5tYn2aKve13psfy"),
    :track_ids => SpTrackId.(["0WdUHon5tYn2aKve13psfy", "619OpJGKpAOrp5rM4Gcs65"]),
    :type => "artist",
    :user_id => "smedjan",
    )