Dict{Symbol, Any}(
    :album_id => SpId("2O9mD7oKwBnhQZQUAJM6GM"),
    :album_ids => [SpId("2O9mD7oKwBnhQZQUAJM6GM"), SpId("3eLvDNfWAMpytqIp073FEc")],
    :artist_id => SpId("7HGFXtBhRq3g1Ma3nH4Rgv"),
    :artist_ids => SpArtistId.(["2CIMQHirSU0MQqyYHq0eOx", "57dN52uHvrHOxijzpIgu3E", "1vCWHaC5f2uS3yhpwWbIA6"]),
    :category_id => SpCategoryId("party"),
    :country => get_user_country(),
    :episode_id => SpId("7Hyyvc9QaojDudrjXsS06P"),
    :episode_ids => [SpEpisodeId(), SpEpisodeId("7Hyyvc9QaojDudrjXsS06P")],
    :ids => [SpId("74ASZWbe4lXaubB36ztrGX"), SpId("08td7MxkoHQkXnWAYD8d6Q")],
    :include_groups => "album,single,appears_on,compilation",
    :item_type => "artist",
    :limit => 10,
    :locale => "",
    :market => get_user_country(),
    :noffset => 0,
    :offset => 0,
    :playlist_id => SpId("3cEYpjA9oz9GiPac4AsH4n"),
    :q => "Coldplay",
    :seeds => [SpId("4NHQUGzhtTLFvgF5SZesLK"), SpId("79O1dBolRj3Epn1pIZRCsZ")],
    :seeds_dict =>  Dict("seed_artists" => "0YC192cP3KPCRWx8zr8MfZ"),
    :show_id => SpId("72qiPaoDRf8HkGKEChvG5q"),
    :show_ids => [SpId("5AvwZVawapvyhJUIx71pdJ"),SpId("6ups0LMt1G8n81XLlkbsPo"), SpId("5AvwZVawapvyhJUIx71pdJ")],
    :time_range => "medium",
    :timestamp => now(),
    :track_attributes => Dict("max_danceability" => "0.80"), 
    :track_id => SpId("0WdUHon5tYn2aKve13psfy"),
    :track_ids => [SpId("0WdUHon5tYn2aKve13psfy"), SpId("619OpJGKpAOrp5rM4Gcs65")],
    :type => "artist",
    :user_ids => [SpUserId("jmperezperez"), SpUserId("thelinmichael"), SpUserId("wizzler")]    
    )