# OBSOLETE, these are keys in a dictionary, automatically made in src/utils/utilities.jl
[
(:album_id, :market)
(:album_id, :limit, :offset, :market)
(:artist_id)
(:artist_id, :include_groups, :country, :limit, :offset)
(:artist_id, :country)
(:artist_id)
(:category_id, :country, :locale)
(:category_id, :country, :limit , :offset )
(:country, :locale, :limit, :offset)
(:country, :locale, :limit, :offset)
(:country, :locale, :limit, :offset, :timestamp)
(:seeds, :track_attributes, :limit , :market )
(:track_attributes)
(:episode_id, :market)
(:type, :ids)
(:playlist_id, :ids)
(:type, :limit)
(:type, :ids)
(:playlist_id)
(:type, :ids)
(:playlist_id)
(:limit, :offset, :market)
(:limit, :offset)
(:limit, :offset, :market)
(:track_ids)
(:show_ids)
(:album_ids)
(:album_ids)
(:show_ids)
(:track_ids)
(:album_ids)
(:shows_ids)
(:track_ids)
(:offset, :limit, :time_range)
(:offset, :limit, :time_range)
(:show_id, :market)
(:show_id, :market, :limit, :offset)
(:track_id)
(:track_id)
(:track_id, :market)
]